@startuml
start
:Import Data;
:Preprocess Data;
if (Visualization enabled?) then (yes)
  :Analyze and visualize distribution;
else (no)
endif
:Prepare Data with Label;
:Split Training Data;
:Train Model;
if (Evaluate Model enabled) then (yes)
  :Evaluate Model;
else (no)
endif
if (Does model configuration exist
       or overwrite disabled?) then (no)
  :Train Model;
  :Save Model;
else (yes)
  :Load Model;
endif

stop
@enduml
